_wandb:
    value:
        cli_version: 0.19.1
        code_path: code/launch_scientist.py
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 55
                - 95
                - 97
            "2":
                - 1
                - 55
                - 95
                - 97
            "3":
                - 2
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
